import type { Actor } from './actor';
import type { Category } from './category';
import type { Director } from './director';
import type { Episode } from './episode';
import type { Region } from './region';
import type { Studio } from './studio';
import type { Tag } from './tag';

export type Movie = {
    _id: string;
    name: string;
    slug: string;
    origin_name?: string;
    content?: string;
    type: string;
    status: string;
    thumb_url?: string;
    poster_url?: string;
    trailer_url?: string;
    time?: number;
    episode_current?: number;
    episode_total?: number;
    quality?: string;
    language?: string;
    notify?: number;
    showtimes?: number;
    episode_time?: number;
    view_total?: number;
    view_day?: number;
    view_week?: number;
    rating_star?: number;
    rating_count?: number;
    seo_title?: string;
    seo_des?: string;
    seo_key?: string;
    created_at: string;
    updated_at: string;
    deleted_at?: string;
    categories?: Category[];
    regions?: Region[];
    directors?: Director[];
    actors?: Actor[];
    tags?: Tag[];
    episodes?: Episode[];
    studios?: Studio[];
};
